#1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
print(np.__version__)

1.23.5


In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
#a = np.random.random(30)
#a = np.random.random((2,3,5))
a = np.random.random((2,3,5))
a

array([[[0.77789236, 0.0873179 , 0.7545056 , 0.29022305, 0.75144619],
        [0.26716125, 0.8373273 , 0.01669333, 0.94590862, 0.00895691],
        [0.17940974, 0.35608776, 0.48235769, 0.30446656, 0.34272638]],

       [[0.91703912, 0.41412384, 0.66245108, 0.86098366, 0.79489409],
        [0.59768357, 0.40361297, 0.42343868, 0.08024014, 0.91967657],
        [0.16344755, 0.77584247, 0.46123428, 0.2812569 , 0.3594186 ]]])

In [4]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.random.random((5,2,3))
b

array([[[0.3199757 , 0.57828245, 0.97191005],
        [0.38506116, 0.03016965, 0.33206416]],

       [[0.52675899, 0.86625232, 0.22036292],
        [0.56676708, 0.09491048, 0.36534426]],

       [[0.16592127, 0.90302653, 0.09304816],
        [0.8961783 , 0.91253308, 0.16731005]],

       [[0.52473134, 0.14555708, 0.73468485],
        [0.04273931, 0.54731718, 0.53389644]],

       [[0.08786361, 0.88276129, 0.74904569],
        [0.13277235, 0.06463698, 0.4370386 ]]])

In [5]:
#7. Do a and b have the same size? How do you prove that in Python code?
#print(a.size)
#print(b.size)

In [6]:
#8. Are you able to add a and b? Why or why not?
#a+b(sumarlo como tal no ya que el numero de filas no coincide con el numero de columnas)


In [7]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array).
#Assign the transposed array to varialbe "c".
c= b.reshape((2,3,5))


In [8]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d=a+c # Ahora funciona por que coincide la cantidad de filas y columnas



In [9]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
#print(a)
#print("---------------------------------------------------------")
#print(d)

In [10]:
#12. Multiply a and c. Assign the result to e.
e = a*c


In [11]:
#13. Does e equal to a? Why or why not?
# no se si lo estare haciendo mal por que no veo ninguna igualdad entre A y E

In [53]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_mean=np.mean(d)
d_max = np.max(d)
d_min = np.min(d)

In [51]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty((2,3,5))
f

array([[[0.24890665, 0.05049441, 0.73331157, 0.11175362, 0.02267087],
        [0.08871468, 0.44106968, 0.01446063, 0.20844318, 0.00507648],
        [0.01702787, 0.13009462, 0.0800334 , 0.27494138, 0.03189006]],

       [[0.82183056, 0.37790171, 0.11083472, 0.45178511, 0.11570246],
        [0.43910906, 0.01725014, 0.23175527, 0.04283993, 0.08080611],
        [0.14428517, 0.58114145, 0.06123916, 0.0181796 , 0.1570798 ]]])

#16 Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.""

In [55]:
#un compañero me explico esta manera de hacerlo.
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[(d == d_mean)] = 50
f[(d == d_min)] = 0
f[(d == d_max)] = 100
print(f)
print(d)

[[[ 75.  25.  75.  25.  25.]
  [ 25.  75.  25.  75.  25.]
  [  0.  25.  25.  75.  25.]]

 [[100.  75.  25.  75.  75.]
  [ 75.  25.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]]]
[[[1.09786806 0.66560035 1.72641564 0.67528421 0.78161584]
  [0.59922541 1.36408629 0.88294565 1.16627154 0.57572399]
  [0.27432023 0.72143202 0.64827896 1.20749309 0.43577455]]

 [[1.81321742 1.32665692 0.82976112 1.385715   0.94045117]
  [1.33236841 0.44635228 0.97075586 0.61413658 1.00754018]
  [1.04620883 1.52488815 0.59400663 0.34589387 0.7964572 ]]]


In [84]:
f = np.where((d > d_min) & (d < d_mean), 25, f)
f = np.where(d == d_mean, 50, f)
f = np.where((d > d_mean) & (d < d_max), 75, f)
f = np.where(d == d_min, 0, f)
f = np.where(d == d_max, 100, f)
f

array([[[ 75.,  25.,  75.,  25.,  25.],
        [ 25.,  75.,  25.,  75.,  25.],
        [  0.,  25.,  25.,  75.,  25.]],

       [[100.,  75.,  25.,  75.,  75.],
        [ 75.,  25.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.]]])

#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [87]:
f = np.where((d > d_min) & (d < d_mean), "A", f)
f = np.where(d == d_mean, "B", f)
f = np.where((d > d_mean) & (d < d_max), "C", f)
f = np.where(d == d_min, "D", f)
f = np.where(d == d_max, "F", f)
f

array([[['C', 'A', 'C', 'A', 'A'],
        ['A', 'C', 'A', 'C', 'A'],
        ['D', 'A', 'A', 'C', 'A']],

       [['F', 'C', 'A', 'C', 'C'],
        ['C', 'A', 'C', 'A', 'C'],
        ['C', 'C', 'A', 'A', 'A']]], dtype='<U32')